In [1]:
import pandas as pd

In [13]:
df = pd.read_csv("inumet_precipitacion_acumulada_horaria.csv", sep=";")

In [14]:
df.head()

              fecha            estacion_id  precip_horario
0               NaN                    NaN             NaN
1  2020-01-01 00:00  Aeropuerto Melilla G3             0.2
2  2020-01-01 01:00  Aeropuerto Melilla G3             0.0
3  2020-01-01 02:00  Aeropuerto Melilla G3             0.0
4  2020-01-01 03:00  Aeropuerto Melilla G3             0.0

In [15]:
df.columns

Index(['fecha', 'estacion_id', 'precip_horario'], dtype='object')

In [17]:
df.isnull().sum()

fecha             8
estacion_id       6
precip_horario    8
dtype: int64

In [19]:
df.shape

(225286, 3)

In [21]:
(df[df["fecha"].isnull()].index == df[df["precip_horario"].isnull()].index).sum()

8

In [22]:
indeces_null_fk = list(df[df["fecha"].isnull()].index)

count = 0
for index_gr in list(df[df["estacion_id"].isnull()].index):
    if index_gr in indeces_null_fk:
        count += 1
count

6

In [23]:
df_nona = df.dropna(subset=["fecha"])

In [24]:
df_nona.isnull().sum()

fecha             0
estacion_id       0
precip_horario    0
dtype: int64

In [25]:
df_nona.shape

(225278, 3)

In [26]:
df_nona.head()

              fecha            estacion_id  precip_horario
1  2020-01-01 00:00  Aeropuerto Melilla G3             0.2
2  2020-01-01 01:00  Aeropuerto Melilla G3             0.0
3  2020-01-01 02:00  Aeropuerto Melilla G3             0.0
4  2020-01-01 03:00  Aeropuerto Melilla G3             0.0
5  2020-01-01 04:00  Aeropuerto Melilla G3             0.0

In [32]:
df_nona["estacion_id"].unique()

array(['Aeropuerto Melilla G3', 'Mercedes G3', 'Artigas G3', 'Rocha G3',
       'Colonia G3', 'Salto G3', 'Paso de los Toros G3'], dtype=object)

In [28]:
df["fecha"].dtype

dtype('O')

In [31]:
df_nona = df_nona.copy()
df_nona["fecha"] = pd.to_datetime(df_nona["fecha"])

In [34]:
df_nona["fecha"]

1        2020-01-01 00:00:00
2        2020-01-01 01:00:00
3        2020-01-01 02:00:00
4        2020-01-01 03:00:00
5        2020-01-01 04:00:00
                 ...
225280   2026-05-22 00:00:00
225281   2026-05-22 01:00:00
225282   2026-05-22 02:00:00
225283   2026-05-22 03:00:00
225284   2026-05-22 04:00:00
Name: fecha, Length: 225278, dtype: datetime64[ns]