In [1]:
import pandas as pd
from pathlib import Path
dir = Path("../GFQA_v3")

In [2]:
def filtrar_uy_param(file, param_code):
	df = pd.read_csv(dir / file)
	param_only = df[df["Parameter Code"] == param_code]
	param_only_uy = param_only[param_only['GEMS Station Number'].str.startswith("URY", na=False)]
	return param_only_uy

In [3]:
df_ph = filtrar_uy_param("pH.csv", "pH")
df_ph.head()

C:\Users\User\AppData\Local\Temp\ipykernel_17600\419058755.py:2: DtypeWarning: Columns (0: Analysis Method Code, 1: Value Flags) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dir / file)

,GEMS Station Number,Sample Date,Sample Time,Depth,Parameter Code,Analysis Method Code,Value Flags,Value,Unit,Data Quality,Integrated Value,Remark,License Information
921103,URY00006,2018-11-12,11:20,0.3,pH,0,NaN,8.05,---,Fair,NaN,NaN,NaN
921104,URY00006,2018-11-12,23:20,0.3,pH,0,NaN,8.05,---,Fair,NaN,NaN,NaN
921105,URY00006,2018-11-21,10:30,0.3,pH,0,NaN,7.91,---,Fair,NaN,NaN,NaN
921106,URY00006,2018-12-05,10:30,0.3,pH,0,NaN,8.00,---,Fair,NaN,NaN,NaN
921107,URY00006,2019-01-23,11:00,0.3,pH,0,NaN,7.59,---,Fair,NaN,NaN,NaN

In [4]:
df_ecoli = filtrar_uy_param("Indicator_Organism.csv", "ECOLI")
df_ecoli.head()

C:\Users\User\AppData\Local\Temp\ipykernel_17600\419058755.py:2: DtypeWarning: Columns (0: Analysis Method Code, 1: Remark) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dir / file)

,GEMS Station Number,Sample Date,Sample Time,Depth,Parameter Code,Analysis Method Code,Value Flags,Value,Unit,Data Quality,Integrated Value,Remark,License Information
390306,URY00006,2018-11-12,23:20,0.3,ECOLI,ESCT-COLILERT,NaN,0.0,1/100 ml,Fair,NaN,NaN,NaN
390342,URY00006,2022-01-24,11:20,0.3,ECOLI,COLI-MF,NaN,100.0,1/100 ml,Fair,NaN,NaN,NaN
390409,URY00007,2022-01-24,10:15,0.3,ECOLI,COLI-MF,NaN,1200.0,1/100 ml,Fair,NaN,NaN,NaN
390441,URY00008,2018-11-12,08:30,0.3,ECOLI,ESCT-COLILERT,NaN,0.0,1/100 ml,Fair,NaN,NaN,NaN
390482,URY00008,2022-01-24,09:05,0.3,ECOLI,COLI-MF,NaN,400.0,1/100 ml,Fair,NaN,NaN,NaN

In [5]:
df_bod = filtrar_uy_param("Oxygen_Demand.csv", "BOD")
df_bod.head()

C:\Users\User\AppData\Local\Temp\ipykernel_17600\419058755.py:2: DtypeWarning: Columns (0: Analysis Method Code, 1: Value Flags) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dir / file)

,GEMS Station Number,Sample Date,Sample Time,Depth,Parameter Code,Analysis Method Code,Value Flags,Value,Unit,Data Quality,Integrated Value,Remark,License Information
691749,URY00021,2011-03-15,12:10,0.3,BOD,0,NaN,2.2,mg/l,Fair,NaN,NaN,NaN
691750,URY00021,2011-05-03,12:45,0.3,BOD,0,NaN,2.2,mg/l,Fair,NaN,NaN,NaN
691751,URY00021,2011-07-19,13:15,0.3,BOD,0,NaN,4.1,mg/l,Fair,NaN,NaN,NaN
691752,URY00021,2012-01-02,13:05,0.3,BOD,0,NaN,0.9,mg/l,Pending review,NaN,NaN,NaN
691753,URY00021,2012-03-06,00:00,0.3,BOD,0,NaN,2.1,mg/l,Fair,NaN,NaN,NaN

In [6]:
df_bod.dtypes

GEMS Station Number         str
Sample Date                 str
Sample Time                 str
Depth                   float64
Parameter Code              str
Analysis Method Code     object
Value Flags                 str
Value                   float64
Unit                        str
Data Quality                str
Integrated Value        float64
Remark                  float64
License Information     float64
dtype: object

In [17]:
df_tp = filtrar_uy_param("Phosphorus.csv", "TP")
df_tp.head()

C:\Users\User\AppData\Local\Temp\ipykernel_34876\419058755.py:2: DtypeWarning: Columns (0: Analysis Method Code, 1: Remark) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dir / file)

,GEMS Station Number,Sample Date,Sample Time,Depth,Parameter Code,Analysis Method Code,Value Flags,Value,Unit,Data Quality,Integrated Value,Remark,License Information
1312382,URY00021,2011-03-15,12:10,0.3,TP,0,NaN,0.531,mg/l,Fair,NaN,NaN,NaN
1312383,URY00021,2011-05-03,12:45,0.3,TP,0,NaN,0.370,mg/l,Fair,NaN,NaN,NaN
1312384,URY00021,2011-07-19,13:15,0.3,TP,0,NaN,0.221,mg/l,Fair,NaN,NaN,NaN
1312385,URY00021,2012-01-02,13:05,0.3,TP,0,NaN,0.686,mg/l,Fair,NaN,NaN,NaN
1312386,URY00021,2012-03-06,00:00,0.3,TP,0,NaN,1.380,mg/l,Fair,NaN,NaN,NaN

In [19]:
len(df_tp["Sample Date"].unique())

1195

In [ ]:
#y-m-d-hh
#

In [22]:
dff_top = df_tp.drop(columns=["GEMS Station Number", "Sample Date", "Sample Time", "Analysis Method Code", "Value Flags", "Integrated Value", "Remark", "License Information"])

In [23]:
dff_top.head()

         Depth Parameter Code  Value  Unit Data Quality
1312382    0.3             TP  0.531  mg/l         Fair
1312383    0.3             TP  0.370  mg/l         Fair
1312384    0.3             TP  0.221  mg/l         Fair
1312385    0.3             TP  0.686  mg/l         Fair
1312386    0.3             TP  1.380  mg/l         Fair

In [4]:
df_inumet = pd.read_csv("../clima/inumet_humedad_relativa.csv", delimiter=";")

In [5]:
df_inumet.head()

              fecha estacion_id  hum_relativa
0               NaN         NaN           NaN
1  2020-01-01 00:00    Rocha G3          96.0
2  2020-01-01 01:00    Rocha G3          97.0
3  2020-01-01 02:00    Rocha G3          97.0
4  2020-01-01 03:00    Rocha G3          97.0

In [3]:
df_inumet2 = pd.read_csv("../clima/inumet_precipitacion_acumulada_horaria (1).csv", delimiter=";")

In [6]:
df_inumet2 = df_inumet2.drop(index=0)

In [7]:
df_inumet2.head()

              fecha            estacion_id  precip_horario
1  2020-01-01 00:00  Aeropuerto Melilla G3             0.2
2  2020-01-01 01:00  Aeropuerto Melilla G3             0.0
3  2020-01-01 02:00  Aeropuerto Melilla G3             0.0
4  2020-01-01 03:00  Aeropuerto Melilla G3             0.0
5  2020-01-01 04:00  Aeropuerto Melilla G3             0.0